version: '3.2'

services:

  app:
    build: .
    ports:
      - 9001:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  #  frontend:
  #    build: frontend
  #    ports:
  #      - 20080:80
  #    volumes:
  #      # Re-use local composer cache via host-volume
  #      - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #      # Mount source-code for development
  #      - ./:/app
  #
  #  backend:
  #    build: backend
  #    ports:
  #      - 21080:80
  #    volumes:
  #      # Re-use local composer cache via host-volume
  #      - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #      # Mount source-code for development
  #      - ./:/app

  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop_db
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii

  #pgsql:
  #  image: postgres:9.5
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret